language: python
sudo: required

python:
  - "3.6"

# Branches to enbale CI.
branches:
  only:
    - master

install:
  - pip install -r requirements.txt

script:
  # - pytest
  - python main.py

after_success:
  - ./docs.sh

notifications:
# slack channel notification
    slack: bisoncorps:urrq42VfAo4zJP2r6lH2dU8Y